services:

  service-db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5532:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: