services:
#  task-service:
#    image: pavelsha/async-course-2023-accounting:1.0.0
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - service-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/accounting-db

  service-db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "7432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: